version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  user_app:
    build: ./users_app
    container_name: users-container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  event_app:
    build: ./events_app
    container_name: events-container
    ports:
      - "5050:5050"
    depends_on:
      - mongodb

  flutter_web_app:
    build: ./expense_splitter_web_app
    container_name: flutter-web-container
    ports:
      - "8080:80"
    depends_on:
      - user_app
      - event_app

volumes:
  mongodb_data:
